### ISSUE TITLE
 mini map with your pings

### ISSUE THREAD

**Issue by IviugaI** [WolfoIsBestWolf/ror2-WolfoQualityoLlife#1]
Have you thought about combining your mod with a mod for the minimap (https://thunderstore.io/package/DekuDesu/MiniMapMod/), in my opinion it would work out very well :)

**Comment by WolfoIsBestWolf** [comment]
I just use the system the game already uses, up to other mod makers to just use the system the game uses so I think they'd need to be the one to add it.
