### ISSUE TITLE
The changed names for Lunar Chimerae do not display their lore properly.

### ISSUE THREAD

**Issue by SlawekNowy** [WolfoIsBestWolf/ror2-WolfoQualityoLlife#2]
![20240506162710_1](https://github.com/WolfoIsBestWolf/ror2-WolfoQualityoLlife/assets/38943477/80f1b1f1-e9d3-4441-9c02-b5f2178f075f)

**Comment by WolfoIsBestWolf** [comment]
Strange issue but will be fixed next patch.
