### ISSUE TITLE
Devotion Update: Cannot activate any interactable.

### ISSUE THREAD

**Issue by SlawekNowy** [WolfoIsBestWolf/ror2-WolfoQualityoLlife#3]
[LogOutput.log](https://github.com/WolfoIsBestWolf/ror2-WolfoQualityoLlife/files/15386668/LogOutput.log)

**Comment by WolfoIsBestWolf** [comment]
Can't replicate it. CommandQueue seems to fail loading maybe it has something to do with it. Other people have similar issues with random mods too so not much I can do.
