### ISSUE TITLE
Vields text

### ISSUE THREAD

**Issue by Phreelosu** [WolfoIsBestWolf/ror2-WolfoQualityoLlife#4]
hey wolfo hope you are doing well. This is more of a feature request than an issue, so feel free to assign enhancement or "wontfix", up to you.

BetterUI is gone thankfully, but it had one QoL thing that I really miss, which was void fields warnings text about what was integrated into the cell each wave as the two screenshots show them exactly.
Any chance you could add this feature into WolfoQoL?

![image](https://github.com/user-attachments/assets/38b4c91d-1c2f-4d7f-9b9b-c517a186fc21)
![image](https://github.com/user-attachments/assets/f95216de-f282-441f-8023-8d82bbf7b099)

**Comment by WolfoIsBestWolf** [comment]
This always was and still is part of the base game.
