### ISSUE TITLE
The shipping request form reminder does not disappear when collecting the item from the terminal

### ISSUE THREAD

**Issue by TwinGalaxy** [WolfoIsBestWolf/ror2-WolfoQualityoLlife#7]
As the title says, when you get the shipping request form item and go to the next stage, where the reminder and the intractable then appear, interacting with the delivery and getting the item from it does not check off the reminder, and the reminder remains for the rest of the stage.
The mod is up-to-date on my end and I did some testing with Aerolt to make sure it wasn't a weird niche case.

**Comment by WolfoIsBestWolf** [comment]
somehow started checking for the wrong value at some point.   it's fixed now in
